<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sales Report - {{ $developer->name }}</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; color: #333; padding: 20px; }
        h1 { color: #1e293b; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
        .header { margin-bottom: 30px; }
        .header p { color: #666; margin: 5px 0; }
        .summary { display: flex; gap: 20px; margin-bottom: 30px; }
        .summary-box { flex: 1; background: #f1f5f9; padding: 15px; border-radius: 8px; border-left: 4px solid #3b82f6; }
        .summary-box h3 { margin: 0 0 5px 0; color: #666; font-size: 14px; }
        .summary-box p { margin: 0; font-size: 24px; font-weight: bold; color: #1e293b; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #1e293b; color: white; padding: 10px; text-align: left; font-size: 12px; }
        td { padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 12px; }
        tr:nth-child(even) { background: #f8fafc; }
        .footer { margin-top: 40px; text-align: center; color: #999; font-size: 11px; border-top: 1px solid #e2e8f0; padding-top: 15px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Nebula Store - Sales Report</h1>
        <p><strong>Developer:</strong> {{ $developer->name }}</p>
        <p><strong>Generated:</strong> {{ now()->format('F d, Y H:i') }}</p>
    </div>

    <div class="summary">
        <div class="summary-box">
            <h3>Total Sales</h3>
            <p>{{ $totalSales }}</p>
        </div>
        <div class="summary-box" style="border-left-color: #8b5cf6;">
            <h3>Net Revenue (95%)</h3>
            <p>Rp {{ number_format($totalRevenue, 0, ',', '.') }}</p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Game Title</th>
                <th style="text-align: center;">Total Sales</th>
                <th style="text-align: right;">Gross Revenue</th>
                <th style="text-align: right;">Net Revenue</th>
                <th style="text-align: center;">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($gameStats as $game)
                <tr>
                    <td>{{ $game->title }}</td>
                    <td style="text-align: center;">{{ $game->total_sales }}</td>
                    <td style="text-align: right;">Rp {{ number_format($game->revenue, 0, ',', '.') }}</td>
                    <td style="text-align: right;">Rp {{ number_format($game->net_revenue, 0, ',', '.') }}</td>
                    <td style="text-align: center;">{{ ucfirst($game->status) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Nebula Store System | This is an official sales report</p>
    </div>
</body>
</html>
